### ISSUE TITLE
RFC

### ISSUE THREAD

**Issue by mattcanty** [mattcanty/golang-extensible-plugin-example#1]
@Kyslik

What do you make of this? I've committed all files on purpose. Trying to figure out ways loading up plugins with different config schemas, however all the config is from a single file.

Simple strings appear to be working, but I may need a few minutes later on today to figure out the map!

`go run main.go` output:

```
This is a test application to demonstrate loading plugins at runtime.
plugin-1 init().
plugin-1 Load().
plugin-1 ReadChanges().
  Will print message: Hello, world!
plugin-1 WriteChanges().
  Hello, world!
plugin-2 init().
plugin-1 Load().
plugin-2 ReadChanges().
  I know the secret
plugin-2 WriteChanges().
  shhhhhh
plugin-3 init().
plugin-1 Load().
2020/03/15 12:14:06 Failed to Unmarshal YAMl. yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into []main.nestedItem
exit status 1
```

**Comment by Kyslik** [comment]
Got confused by https://github.com/mattcanty/golang-extensible-plugin-example/blob/master/plugins/plugin-3/main.go#L26

Will take a look.

**Comment by Kyslik** [comment]
> Simple strings appear to be working, but I may need a few minutes later on today to figure out the map!

@mattcanty it's because your YAML is not correct:

```yaml
plugins:
  - name: plugin-3
    parameters: |
      nestedStuff:
        - name: Nested Name
```

```sh
go run main.go
This is a test application to demonstrate loading plugins at runtime.
plugin-3 init().
plugin-3 Load().
plugin-3 ReadChanges().
plugin-3 WriteChanges().
```

**Comment by mattcanty** [comment]
Typo in the print, and I think I was aiming for not an array so I’ll fix
the struct.

This would work Gobee, but I don’t like the parameters as a string in the
config file... mainly because you lose the syntax highlighting and lint
check capability.

Will look into alternatives like TOML.

**Comment by Kyslik** [comment]
> This would work Gobee, but I don’t like the parameters as a string in the
config file... mainly because you lose the syntax highlighting and lint
check capability.

Same here. Thinking how to _combat_ that.

**Comment by mattcanty** [comment]
Pretty happy with the improvement I just made, although it doesn't help with the string parameters. 

What it does do though is require every plugin to adhere to the following public variables:

- struct PluginConfig
- func ReadChanges
- func WriteChanges

Also the loading of PluginConfig is done in the main execution!
https://github.com/mattcanty/golang-extensible-plugin-example/blob/master/main.go#L49
